Repository nhs-r-community/NHSRplotthedots, pull requests merged in 2021-09, with the labels that each got.

#73 support tidyeval
  R/ptd_spc.R
  R/ptd_spc_colours.R
  man/ptd_spc.Rd
  tests/testthat/test-ptd_spc.R
  vignettes/intro.Rmd
Labels: enhancement

#83 updates the readme to use NSE
  README.Rmd
  README.md
Labels: documentation

#88 Issue #84 - fixes target and trajectory line colours
  R/ptd_spc_colours.R
  man/ptd_spc_colours.Rd
  tests/testthat/test-ptd_spc.R
Labels: bug

#89 Closes issue #54 implement purple neutral special cause
  DESCRIPTION
  R/ptd_calculate_point_type.R
  R/ptd_create_ggplot.R
  R/ptd_spc.R
  R/ptd_spc_colours.R
  R/ptd_spc_options.R
  man/ptd_spc.Rd
  man/ptd_spc_colours.Rd
  tests/testthat/test-ptd_calculate_point_type.R
  tests/testthat/test-ptd_create_ggplot.R
  tests/testthat/test-ptd_spc_options.R
Labels: enhancement
